apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-nspc-sa
  namespace: app-nspc
  labels:
    app: app-nspc
automountServiceAccountToken: false  # Не монтируем токен — приложению не нужен K8s API